### ISSUE TITLE
snap manual connect to bluetooth-control fails

### ISSUE THREAD

**Issue by saket424** [anonymouse64/thingy52-snap#1]
@anonymouse64.

I attempted using your snap on both raspbian32 and raspbian64  on a pi4 without success

snap install thingy52 --classic
Warning: flag --classic ignored for strictly confined snap thingy52

thingy52 1.0 from Ian Johnson (anonymouse67) installed

sudo snap connect thingy52:
bluetooth-control  network            network-bind       
pi@pi400key:~/thingy-stuff/thingy52-snap $ sudo snap connect thingy52:bluetooth-control 
error: cannot resolve connection, slot snap name is empty

I am obviously doing something wrong. Any ideas for me to try ?

**Comment by saket424** [comment]
I am using raspbian buster and 2.37.4 of snapd

dpkg -l | grep snapd
ii  snapd                                2.37.4-1+rpi1                       armhf        Daemon and tooling that enable snap packages
pi@pi400key:~/thingy-stuff/thingy52-snap $ uname -a
Linux pi400key 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux

**Comment by anonymouse64** [comment]
Please update snapd by running the following:

```
snap install core
```

And then try again

**Comment by saket424** [comment]
Success !! Thanks for the prompt response.

After I did 'snap install core; snap install thingy52'

pi@pitop1:~ $ snap install thingy52
thingy52 1.0 from Ian Johnson (anonymouse67) installed
pi@pitop1:~ $ thingy52
usage: thingy52 [-h] [-n COUNT] [-t T] [--temperature] [--pressure]
                [--humidity] [--gas] [--color] [--keypress] [--tap]
                [--orientation] [--quaternion] [--stepcnt] [--rawdata]
                [--euler] [--rotation] [--heading] [--gravity] [--battery]
                [--speaker] [--microphone]
                mac_address
thingy52: error: the following arguments are required: mac_address
pi@pitop1:~ $ thingy52 -n 5 --temperature --pressure F1:BB:80:AC:XD:E2
Connecting to F1:BB:80:AC:XD:E2
Connected...
LED set to breathe mode...
Enabling selected sensors...
Notification: Temp received:  23.12 degCelcius
Notification: Temp received:  23.4 degCelcius
All requested sensors and notifications are enabled...
Notification: Press received: 996.49 hPa
Notification: Temp received:  23.21 degCelcius
Notification: Press received: 996.42 hPa
Notification: Temp received:  22.82 degCelcius
pi@pitop1:~ $

**Comment by anonymouse64** [comment]
I did make a change to the snap which will prevent it from being installed on a system with an old snapd, there you will get a message about needing to update the core snap which should prevent future users from running into this problem.
