### ISSUE TITLE
Is there a re-connect mode planned?

### ISSUE THREAD

**Issue by saket424** [anonymouse64/thingy52-snap#2]
The connection is unreliable or the code exits due to parsing errors as illustrated below. What is the preferred way if I want to continually query the sensor for updates reliably (maybe once a minute or once in ten minutes) ?

thingy52 -n 5000000 --temperature --pressure --humidity --gas --battery F1:BB:80:AC:XD:E2
Connecting to F1:BB:80:AC:XD:E2
Connected...
LED set to breathe mode...
Enabling selected sensors...
Notification: Temp received:  23.17 degCelcius
Notification: Temp received:  23.32 degCelcius
Notification: Press received: 996.38 hPa
Notification: Temp received:  23.53 degCelcius
Notification: Press received: 996.45 hPa
Notification: Humidity received: 38 %
Notification: Temp received:  23.32 degCelcius
Notification: Humidity received: 35 %
Notification: Press received: 996.47 hPa
All requested sensors and notifications are enabled...
Notification: Temp received:  22.98 degCelcius
Notification: Humidity received: 37 %
Notification: Press received: 996.47 hPa
Battery:  84
Notification: Temp received:  23.44 degCelcius
Notification: Humidity received: 37 %
Notification: Press received: 996.39 hPa
Battery:  84
Notification: Gas received: eCO2 ppm: 0, TVOC ppb: 0 %
Battery:  84
Notification: Temp received:  22.83 degCelcius
Notification: Humidity received: 37 %
Notification: Press received: 996.43 hPa
Battery:  82
Notification: Gas received: eCO2 ppm: 0, TVOC ppb: 0 %
Battery:  82
Notification: Temp received:  23.60 degCelcius
Notification: Humidity received: 37 %
Notification: Press received: 996.47 hPa
Battery:  82
Notification: Gas received: eCO2 ppm: 0, TVOC ppb: 0 %
Battery:  82
Notification: Temp received:  23.60 degCelcius
Notification: Humidity received: 37 %
Notification: Press received: 996.45 hPa
Notification: Gas received: eCO2 ppm: 346, TVOC ppb: 0 %
Battery:  82
Notification: Temp received:  23.34 degCelcius
Notification: Humidity received: 36 %
Notification: Press received: 996.54 hPa
Notification: Gas received: eCO2 ppm: 346, TVOC ppb: 0 %
Battery:  82
Notification: Temp received:  23.83 degCelcius
Notification: Humidity received: 36 %
Notification: Press received: 996.34 hPa
Battery:  82
Notification: Gas received: eCO2 ppm: 346, TVOC ppb: 0 %
Battery:  82
Notification: Temp received:  22.98 degCelcius
Notification: Humidity received: 37 %
Notification: Press received: 996.38 hPa
Battery:  81
Notification: Gas received: eCO2 ppm: 346, TVOC ppb: 0 %
Battery:  81
Notification: Temp received:  23.53 degCelcius
Notification: Humidity received: 39 %
Notification: Press received: 996.36 hPa
Notification: Gas received: eCO2 ppm: 346, TVOC ppb: 0 %
Battery:  81
Notification: Temp received:  23.49 degCelcius
Notification: Humidity received: 36 %
Notification: Press received: 996.41 hPa
Notification: Gas received: eCO2 ppm: 351, TVOC ppb: 0 %
Battery:  81
Notification: Temp received:  23.32 degCelcius
Notification: Humidity received: 39 %
Notification: Press received: 996.38 hPa
Traceback (most recent call last):
  File "/snap/thingy52/40/bin/thingy52", line 33, in <module>
    sys.exit(load_entry_point('bluepy==1.3.0', 'console_scripts', 'thingy52')())
  File "/snap/thingy52/40/lib/python3.6/site-packages/bluepy/thingy52.py", line 819, in main
    print("Battery: ", thingy.battery.read())
  File "/snap/thingy52/40/lib/python3.6/site-packages/bluepy/thingy52.py", line 107, in read
    val = ord(self.data.read())
  File "/snap/thingy52/40/lib/python3.6/site-packages/bluepy/btle.py", line 197, in read
    return self.peripheral.readCharacteristic(self.valHandle)
  File "/snap/thingy52/40/lib/python3.6/site-packages/bluepy/btle.py", line 530, in readCharacteristic
    resp = self._getResp('rd')
  File "/snap/thingy52/40/lib/python3.6/site-packages/bluepy/btle.py", line 416, in _getResp
    self.delegate.handleNotification(hnd, data)
  File "/snap/thingy52/40/lib/python3.6/site-packages/bluepy/thingy52.py", line 594, in handleNotification
    eco2, tvoc = self._extract_gas_data(data)
  File "/snap/thingy52/40/lib/python3.6/site-packages/bluepy/thingy52.py", line 673, in _extract_gas_data
    eco2 = int(teptep[:2]) + (int(teptep[2:4]) << 8)
ValueError: invalid literal for int() with base 10: b'9d'

pi@pitop1:~ $ thingy52 -n 0 --temperature --pressure --humidity --gas --battery F1:BB:80:AC:XD:E2
Connecting to F1:BB:80:AC:XD:E2
Traceback (most recent call last):
  File "/snap/thingy52/40/bin/thingy52", line 33, in <module>
    sys.exit(load_entry_point('bluepy==1.3.0', 'console_scripts', 'thingy52')())
  File "/snap/thingy52/40/lib/python3.6/site-packages/bluepy/thingy52.py", line 730, in main
    thingy = Thingy52(args.mac_address)
  File "/snap/thingy52/40/lib/python3.6/site-packages/bluepy/thingy52.py", line 692, in __init__
    Peripheral.__init__(self, addr, addrType=ADDR_TYPE_RANDOM)
  File "/snap/thingy52/40/lib/python3.6/site-packages/bluepy/btle.py", line 391, in __init__
    self._connect(deviceAddr, addrType, iface)
  File "/snap/thingy52/40/lib/python3.6/site-packages/bluepy/btle.py", line 439, in _connect
    raise BTLEDisconnectError("Failed to connect to peripheral %s, addr type: %s" % (addr, addrType), rsp)
bluepy.btle.BTLEDisconnectError: Failed to connect to peripheral F1:BB:80:AC:AD:E2, addr type: random

pi@pitop1:~ $ thingy52 -n 0 --temperature --pressure --humidity --gas --battery F1:BB:80:AC:XD:E2
Connecting to F1:BB:80:AC:XD:E2
Connected...
LED set to breathe mode...
Enabling selected sensors...
Notification: Temp received:  23.19 degCelcius
Notification: Temp received:  23.34 degCelcius
Notification: Press received: 996.50 hPa
Notification: Temp received:  23.34 degCelcius
Notification: Press received: 996.46 hPa
Notification: Humidity received: 38 %
Notification: Temp received:  23.8 degCelcius
Notification: Humidity received: 38 %
Notification: Press received: 996.43 hPa
All requested sensors and notifications are enabled...
Notification: Temp received:  23.12 degCelcius
Notification: Humidity received: 38 %
Notification: Press received: 996.44 hPa
Battery:  84
pi@pitop1:~ $

**Comment by anonymouse64** [comment]
Unfortunately that's kinda been my experience with this hardware is that sometimes it just seems to want to disconnect when used with this python program, I did have better luck keeping it connected with some custom Go code I wrote which used bluez, but even that would still sometimes randomly get disconnected and needed to have reconnection logic built-in to it. 

For this project specifically you are probably better off filing a bug upstream about this: https://github.com/IanHarvey/bluepy.git

**Comment by saket424** [comment]
I have found (illustrated in the log above) that even for a single one-shot reading the connection isn't established reliably. If your custom go code can initiate the initialconnection for a one shot reading reliably, I would be all ears and willing to give it a whirl.

**Comment by anonymouse64** [comment]
so the main codebase was written for an EdgeX device service (see https://docs.edgexfoundry.org/1.2/microservices/device/Ch-DeviceServices/), but if you're familiar with Go code, you can probably hack it into a simpler thing that's not integrated with EdgeX easily, this is the main bit of code that uses bluez / dbus to talk to the device over bluetooth: https://github.com/anonymouse64/device-thingy52/blob/master/internal/driver/thingy52.go, and how to use that code from a larger go program is something like the code here: https://github.com/anonymouse64/device-thingy52/blob/master/internal/driver/thingy52driver.go#L91-L180

that code currently just handles the heading/motion characteristic, but you could probably adapt the python code for other characteristics to handle whatever you're interested in
